apiVersion: api.sayedimran.com/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: scaler
    app.kubernetes.io/instance: scaler-sample
    app.kubernetes.io/part-of: scaler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: scaler
  name: scaler-sample
spec:
  start: 5
  end: 10
  deployments:
  - name: micro-1
    namespace: default
    replicas: 3
  - name: micro-2
    namespace: default
    replicas: 2
